# https://taskfile.dev

version: '2'

vars:
  GREETING: Reference repo for managing mutli repo constallations

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l # show-task: true
    silent: true

  sys:which:
    desc: _
    cmds:
      - echo $(pwd)
      - echo $(realpath Taskfile.yml)

  repos:list:
    desc: _
    cmds:
      - echo "- https://github.com/gzvulon/python-fire.git"
    silent: true

  bundles:list:
    desc: _
    cmds:
      - |
        echo "
        libs_python:
          $(task repos:show)
        "
    silent: true

  bundles:pull:
    desc: _
    vars:
      target: libs_python
    cmds:
      - echo "using bundle {{.target}}"
      - mkdir ../{{.target}}
      - git -C ../{{.target}} clone https://github.com/gzvulon/python-fire.git

