# https://taskfile.dev

version: '2'

vars:
  GREETING: Reference repo for managing mutli repo constallations
  TWDIR:
    sh: dirname $(realpath Taskfile.yml)
    #echo "$(dirname $(which realpath && realpath Taskfile.yml || readlink -f Taskfile.yml))"

_user_:
  def_props: &r_def_props
    desc: _
    dir: "{{.TWDIR}}"

tasks:
  default:
    <<: *r_def_props
    cmds:
      - echo "{{.GREETING}}"
      - task -l # show-task: true
    silent: true

  sys:which:
    <<: *r_def_props
    cmds:
      - echo "{{.TWDIR}}"
      - echo $(pwd)
      - echo $(realpath Taskfile.yml)

  repos:list:
    <<: *r_def_props
    cmds:
      - echo "- https://github.com/gzvulon/python-fire.git"
    silent: true

  bundles:list:
    <<: *r_def_props
    cmds:
      - |
        echo "
        libs_python:
          $(task repos:show)
        "
    silent: true

  bundles:pull:
    <<: *r_def_props
    vars:
      target: libs_python
    cmds:
      - echo "using bundle {{.target}}"
      - mkdir ../{{.target}}
      - git -C ../{{.target}} clone https://github.com/gzvulon/python-fire.git

